# Generated by Django 5.0 on 2024-06-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Sid', models.IntegerField()),
                ('Registerd', models.CharField(default='No', max_length=20)),
                ('Registerd_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Tid', models.IntegerField()),
                ('Registerd', models.CharField(default='No', max_length=20)),
                ('Registerd_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
