# Generated by Django 5.0 on 2024-06-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_semester_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Sid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Tid',
            field=models.IntegerField(unique=True),
        ),
    ]
